=begin
#dlpapi

#Easily and directly scan and detect sensitive data (PII) in input text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'date'

module CloudmersiveDlpApiClient
  # Request object for DLP document redaction with 23 PII detection types.
  class DlpDocumentRedactionRequest
    # Document file bytes (PDF, DOCX, PNG, or JPG) to scan for PII and redact.
    attr_accessor :input_file

    # Optional. Name of the input file including extension, used for format detection. If not provided, format is detected from file contents.
    attr_accessor :file_name

    # Optional. Recognition mode for image processing. Options: null (default), \"Fast\", \"FastPlus\", \"FastMini\".
    attr_accessor :recognition_mode

    # Redaction mode for PII regions. Options: \"BlackOut\" (default) draws black rectangles over PII rows, \"Blur\" applies Gaussian blur to PII rows, \"BlackOutEntirePage\" blacks out entire dirty pages, \"BlurEntirePage\" blurs entire dirty pages.
    attr_accessor :redaction_mode

    # Set to true to allow email addresses in the document and not redact them.
    attr_accessor :allow_email_address

    # Set to true to allow phone numbers in the document and not redact them.
    attr_accessor :allow_phone_number

    # Set to true to allow street addresses in the document and not redact them.
    attr_accessor :allow_street_address

    # Set to true to allow person names in the document and not redact them.
    attr_accessor :allow_person_name

    # Set to true to allow birth dates in the document and not redact them.
    attr_accessor :allow_birth_date

    # Set to true to allow passport numbers in the document and not redact them.
    attr_accessor :allow_passport_number

    # Set to true to allow drivers license numbers in the document and not redact them.
    attr_accessor :allow_drivers_license

    # Set to true to allow social security numbers in the document and not redact them.
    attr_accessor :allow_social_security_number

    # Set to true to allow taxpayer IDs in the document and not redact them.
    attr_accessor :allow_taxpayer_id

    # Set to true to allow credit card numbers in the document and not redact them.
    attr_accessor :allow_credit_card_number

    # Set to true to allow credit card expiration dates in the document and not redact them.
    attr_accessor :allow_credit_card_expiration_date

    # Set to true to allow credit card verification codes in the document and not redact them.
    attr_accessor :allow_credit_card_verification_code

    # Set to true to allow bank account numbers in the document and not redact them.
    attr_accessor :allow_bank_account_number

    # Set to true to allow IBANs in the document and not redact them.
    attr_accessor :allow_iban

    # Set to true to allow health insurance numbers in the document and not redact them.
    attr_accessor :allow_health_insurance_number

    # Set to true to allow bearer tokens in the document and not redact them.
    attr_accessor :allow_bearer_token

    # Set to true to allow HTTP cookies in the document and not redact them.
    attr_accessor :allow_http_cookie

    # Set to true to allow private keys in the document and not redact them.
    attr_accessor :allow_private_keys

    # Set to true to allow credentials (usernames/passwords) in the document and not redact them.
    attr_accessor :allow_credentials

    # Set to true to allow deep web URLs (.onion) in the document and not redact them.
    attr_accessor :allow_deep_web_urls

    # Set to true to allow source code in the document and not redact it.
    attr_accessor :allow_source_code

    # Set to true to allow IP addresses in the document and not redact them.
    attr_accessor :allow_ip_address

    # Set to true to allow MAC addresses in the document and not redact them.
    attr_accessor :allow_mac_address

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'input_file' => :'InputFile',
        :'file_name' => :'FileName',
        :'recognition_mode' => :'RecognitionMode',
        :'redaction_mode' => :'RedactionMode',
        :'allow_email_address' => :'AllowEmailAddress',
        :'allow_phone_number' => :'AllowPhoneNumber',
        :'allow_street_address' => :'AllowStreetAddress',
        :'allow_person_name' => :'AllowPersonName',
        :'allow_birth_date' => :'AllowBirthDate',
        :'allow_passport_number' => :'AllowPassportNumber',
        :'allow_drivers_license' => :'AllowDriversLicense',
        :'allow_social_security_number' => :'AllowSocialSecurityNumber',
        :'allow_taxpayer_id' => :'AllowTaxpayerID',
        :'allow_credit_card_number' => :'AllowCreditCardNumber',
        :'allow_credit_card_expiration_date' => :'AllowCreditCardExpirationDate',
        :'allow_credit_card_verification_code' => :'AllowCreditCardVerificationCode',
        :'allow_bank_account_number' => :'AllowBankAccountNumber',
        :'allow_iban' => :'AllowIBAN',
        :'allow_health_insurance_number' => :'AllowHealthInsuranceNumber',
        :'allow_bearer_token' => :'AllowBearerToken',
        :'allow_http_cookie' => :'AllowHttpCookie',
        :'allow_private_keys' => :'AllowPrivateKeys',
        :'allow_credentials' => :'AllowCredentials',
        :'allow_deep_web_urls' => :'AllowDeepWebUrls',
        :'allow_source_code' => :'AllowSourceCode',
        :'allow_ip_address' => :'AllowIpAddress',
        :'allow_mac_address' => :'AllowMacAddress'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'input_file' => :'String',
        :'file_name' => :'String',
        :'recognition_mode' => :'String',
        :'redaction_mode' => :'String',
        :'allow_email_address' => :'BOOLEAN',
        :'allow_phone_number' => :'BOOLEAN',
        :'allow_street_address' => :'BOOLEAN',
        :'allow_person_name' => :'BOOLEAN',
        :'allow_birth_date' => :'BOOLEAN',
        :'allow_passport_number' => :'BOOLEAN',
        :'allow_drivers_license' => :'BOOLEAN',
        :'allow_social_security_number' => :'BOOLEAN',
        :'allow_taxpayer_id' => :'BOOLEAN',
        :'allow_credit_card_number' => :'BOOLEAN',
        :'allow_credit_card_expiration_date' => :'BOOLEAN',
        :'allow_credit_card_verification_code' => :'BOOLEAN',
        :'allow_bank_account_number' => :'BOOLEAN',
        :'allow_iban' => :'BOOLEAN',
        :'allow_health_insurance_number' => :'BOOLEAN',
        :'allow_bearer_token' => :'BOOLEAN',
        :'allow_http_cookie' => :'BOOLEAN',
        :'allow_private_keys' => :'BOOLEAN',
        :'allow_credentials' => :'BOOLEAN',
        :'allow_deep_web_urls' => :'BOOLEAN',
        :'allow_source_code' => :'BOOLEAN',
        :'allow_ip_address' => :'BOOLEAN',
        :'allow_mac_address' => :'BOOLEAN'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'InputFile')
        self.input_file = attributes[:'InputFile']
      end

      if attributes.has_key?(:'FileName')
        self.file_name = attributes[:'FileName']
      end

      if attributes.has_key?(:'RecognitionMode')
        self.recognition_mode = attributes[:'RecognitionMode']
      end

      if attributes.has_key?(:'RedactionMode')
        self.redaction_mode = attributes[:'RedactionMode']
      end

      if attributes.has_key?(:'AllowEmailAddress')
        self.allow_email_address = attributes[:'AllowEmailAddress']
      end

      if attributes.has_key?(:'AllowPhoneNumber')
        self.allow_phone_number = attributes[:'AllowPhoneNumber']
      end

      if attributes.has_key?(:'AllowStreetAddress')
        self.allow_street_address = attributes[:'AllowStreetAddress']
      end

      if attributes.has_key?(:'AllowPersonName')
        self.allow_person_name = attributes[:'AllowPersonName']
      end

      if attributes.has_key?(:'AllowBirthDate')
        self.allow_birth_date = attributes[:'AllowBirthDate']
      end

      if attributes.has_key?(:'AllowPassportNumber')
        self.allow_passport_number = attributes[:'AllowPassportNumber']
      end

      if attributes.has_key?(:'AllowDriversLicense')
        self.allow_drivers_license = attributes[:'AllowDriversLicense']
      end

      if attributes.has_key?(:'AllowSocialSecurityNumber')
        self.allow_social_security_number = attributes[:'AllowSocialSecurityNumber']
      end

      if attributes.has_key?(:'AllowTaxpayerID')
        self.allow_taxpayer_id = attributes[:'AllowTaxpayerID']
      end

      if attributes.has_key?(:'AllowCreditCardNumber')
        self.allow_credit_card_number = attributes[:'AllowCreditCardNumber']
      end

      if attributes.has_key?(:'AllowCreditCardExpirationDate')
        self.allow_credit_card_expiration_date = attributes[:'AllowCreditCardExpirationDate']
      end

      if attributes.has_key?(:'AllowCreditCardVerificationCode')
        self.allow_credit_card_verification_code = attributes[:'AllowCreditCardVerificationCode']
      end

      if attributes.has_key?(:'AllowBankAccountNumber')
        self.allow_bank_account_number = attributes[:'AllowBankAccountNumber']
      end

      if attributes.has_key?(:'AllowIBAN')
        self.allow_iban = attributes[:'AllowIBAN']
      end

      if attributes.has_key?(:'AllowHealthInsuranceNumber')
        self.allow_health_insurance_number = attributes[:'AllowHealthInsuranceNumber']
      end

      if attributes.has_key?(:'AllowBearerToken')
        self.allow_bearer_token = attributes[:'AllowBearerToken']
      end

      if attributes.has_key?(:'AllowHttpCookie')
        self.allow_http_cookie = attributes[:'AllowHttpCookie']
      end

      if attributes.has_key?(:'AllowPrivateKeys')
        self.allow_private_keys = attributes[:'AllowPrivateKeys']
      end

      if attributes.has_key?(:'AllowCredentials')
        self.allow_credentials = attributes[:'AllowCredentials']
      end

      if attributes.has_key?(:'AllowDeepWebUrls')
        self.allow_deep_web_urls = attributes[:'AllowDeepWebUrls']
      end

      if attributes.has_key?(:'AllowSourceCode')
        self.allow_source_code = attributes[:'AllowSourceCode']
      end

      if attributes.has_key?(:'AllowIpAddress')
        self.allow_ip_address = attributes[:'AllowIpAddress']
      end

      if attributes.has_key?(:'AllowMacAddress')
        self.allow_mac_address = attributes[:'AllowMacAddress']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@input_file.nil? && @input_file !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
        invalid_properties.push('invalid value for "input_file", must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@input_file.nil? && @input_file !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] input_file Value to be assigned
    def input_file=(input_file)
      if !input_file.nil? && input_file !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
        fail ArgumentError, 'invalid value for "input_file", must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.'
      end

      @input_file = input_file
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          input_file == o.input_file &&
          file_name == o.file_name &&
          recognition_mode == o.recognition_mode &&
          redaction_mode == o.redaction_mode &&
          allow_email_address == o.allow_email_address &&
          allow_phone_number == o.allow_phone_number &&
          allow_street_address == o.allow_street_address &&
          allow_person_name == o.allow_person_name &&
          allow_birth_date == o.allow_birth_date &&
          allow_passport_number == o.allow_passport_number &&
          allow_drivers_license == o.allow_drivers_license &&
          allow_social_security_number == o.allow_social_security_number &&
          allow_taxpayer_id == o.allow_taxpayer_id &&
          allow_credit_card_number == o.allow_credit_card_number &&
          allow_credit_card_expiration_date == o.allow_credit_card_expiration_date &&
          allow_credit_card_verification_code == o.allow_credit_card_verification_code &&
          allow_bank_account_number == o.allow_bank_account_number &&
          allow_iban == o.allow_iban &&
          allow_health_insurance_number == o.allow_health_insurance_number &&
          allow_bearer_token == o.allow_bearer_token &&
          allow_http_cookie == o.allow_http_cookie &&
          allow_private_keys == o.allow_private_keys &&
          allow_credentials == o.allow_credentials &&
          allow_deep_web_urls == o.allow_deep_web_urls &&
          allow_source_code == o.allow_source_code &&
          allow_ip_address == o.allow_ip_address &&
          allow_mac_address == o.allow_mac_address
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [input_file, file_name, recognition_mode, redaction_mode, allow_email_address, allow_phone_number, allow_street_address, allow_person_name, allow_birth_date, allow_passport_number, allow_drivers_license, allow_social_security_number, allow_taxpayer_id, allow_credit_card_number, allow_credit_card_expiration_date, allow_credit_card_verification_code, allow_bank_account_number, allow_iban, allow_health_insurance_number, allow_bearer_token, allow_http_cookie, allow_private_keys, allow_credentials, allow_deep_web_urls, allow_source_code, allow_ip_address, allow_mac_address].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CloudmersiveDlpApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
