=begin
#dlpapi

#Easily and directly scan and detect sensitive data (PII) in input text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveDlpApiClient::DetectApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DetectApi' do
  before do
    # run before each test
    @instance = CloudmersiveDlpApiClient::DetectApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DetectApi' do
    it 'should create an instance of DetectApi' do
      expect(@instance).to be_instance_of(CloudmersiveDlpApiClient::DetectApi)
    end
  end

  # unit tests for detect_document
  # Detect User Data in Document Image
  # Detects configurable types of user data in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
  # @param [Hash] opts the optional parameters
  # @option opts [DlpDocumentDetectionRequest] :body Input request
  # @return [DlpDetectionResponse]
  describe 'detect_document test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for detect_document_advanced
  # Detect User Data in Document Image (Advanced)
  # Detects 29 configurable types of user data including health-related PHI in a document image (PDF, DOCX, PNG, JPG) using Advanced AI.
  # @param [Hash] opts the optional parameters
  # @option opts [DlpAdvancedDocumentDetectionRequest] :body Input request
  # @return [DlpAdvancedDetectionResponse]
  describe 'detect_document_advanced test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for detect_text
  # Detect User Data in Input Text
  # Detects configurable types of user data in an input text string using Advanced AI.
  # @param [Hash] opts the optional parameters
  # @option opts [DlpDetectionRequest] :body Input request
  # @return [DlpDetectionResponse]
  describe 'detect_text test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for detect_text_advanced
  # Detect User Data in Input Text (Advanced)
  # Detects 29 configurable types of user data including health-related PHI in an input text string using Advanced AI.
  # @param [Hash] opts the optional parameters
  # @option opts [DlpAdvancedDetectionRequest] :body Input request
  # @return [DlpAdvancedDetectionResponse]
  describe 'detect_text_advanced test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
