=begin
#dlpapi

#Easily and directly scan and detect sensitive data (PII) in input text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveDlpApiClient::RedactApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RedactApi' do
  before do
    # run before each test
    @instance = CloudmersiveDlpApiClient::RedactApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RedactApi' do
    it 'should create an instance of RedactApi' do
      expect(@instance).to be_instance_of(CloudmersiveDlpApiClient::RedactApi)
    end
  end

  # unit tests for redact_document
  # Redact User Data in Document
  # Detects and redacts configurable types of user data in a document (PDF, DOCX, PNG, JPG) using Advanced AI. Rasterizes document pages, detects PII regions using a grid-overlay approach, blurs those regions, and returns a rasterized PDF.
  # @param [Hash] opts the optional parameters
  # @option opts [DlpDocumentRedactionRequest] :body Input request
  # @return [DlpDocumentRedactionResponse]
  describe 'redact_document test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for redact_document_advanced
  # Redact User Data in Document (Advanced)
  # Detects and redacts 35 configurable types of user data including health-related PHI in a document (PDF, DOCX, PNG, JPG) using Advanced AI. Rasterizes document pages, detects PII regions using a row-overlay approach, redacts those regions, and returns a rasterized PDF.
  # @param [Hash] opts the optional parameters
  # @option opts [DlpAdvancedDocumentRedactionRequest] :body Input request
  # @return [DlpAdvancedDocumentRedactionResponse]
  describe 'redact_document_advanced test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for redact_text
  # Redact User Data in Input Text
  # Detects and redacts configurable types of user data in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
  # @param [Hash] opts the optional parameters
  # @option opts [DlpRedactionRequest] :body Input request
  # @return [DlpRedactionResponse]
  describe 'redact_text test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for redact_text_advanced
  # Redact User Data in Input Text (Advanced)
  # Detects and redacts 34 configurable types of user data including health-related PHI in an input text string using Advanced AI. First detects PII, then redacts disallowed types by either deleting them or replacing them with asterisks.
  # @param [Hash] opts the optional parameters
  # @option opts [DlpAdvancedRedactionRequest] :body Input request
  # @return [DlpAdvancedRedactionResponse]
  describe 'redact_text_advanced test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
