=begin
#dlpapi

#Easily and directly scan and detect sensitive data (PII) in input text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveDlpApiClient::TasksBatchJobApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TasksBatchJobApi' do
  before do
    # run before each test
    @instance = CloudmersiveDlpApiClient::TasksBatchJobApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TasksBatchJobApi' do
    it 'should create an instance of TasksBatchJobApi' do
      expect(@instance).to be_instance_of(CloudmersiveDlpApiClient::TasksBatchJobApi)
    end
  end

  # unit tests for detect_audio_advanced_batch_job
  # Detect User Data in Audio File (Advanced) as a Batch Job
  # Creates an async batch job for detecting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 29 configurable types of user data including health-related PHI in the transcript using Advanced AI. Returns the full transcript, token timestamps, detection results, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
  # @param [Hash] opts the optional parameters
  # @option opts [DlpAdvancedAudioDetectionRequest] :body Input request
  # @return [DlpBatchJobResult]
  describe 'detect_audio_advanced_batch_job test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for detect_audio_batch_job
  # Detect User Data in Audio File as a Batch Job
  # Creates an async batch job for detecting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA) and detects 23 configurable types of user data in the transcript using Advanced AI. Returns the full transcript, token timestamps, and detection results.  Requires Managed Instance or Private Cloud deployment.
  # @param [Hash] opts the optional parameters
  # @option opts [DlpAudioDetectionRequest] :body Input request
  # @return [DlpBatchJobResult]
  describe 'detect_audio_batch_job test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_async_job_status
  # Get the status and result of a DLP Batch Job
  # Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (detection or redaction result) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :async_job_id Job ID for the batch job to get the status of
  # @return [DlpBatchJobStatusResult]
  describe 'get_async_job_status test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for redact_audio_advanced_batch_job
  # Redact User Data in Audio File (Advanced) as a Batch Job
  # Creates an async batch job for redacting user data in an audio file using Advanced detection.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 34 configurable types of user data including health-related PHI in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, redacted segment timestamps, and optional rationale.  Requires Managed Instance or Private Cloud deployment.
  # @param [Hash] opts the optional parameters
  # @option opts [DlpAdvancedAudioRedactionRequest] :body Input request
  # @return [DlpBatchJobResult]
  describe 'redact_audio_advanced_batch_job test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for redact_audio_batch_job
  # Redact User Data in Audio File as a Batch Job
  # Creates an async batch job for redacting user data in an audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the redacted audio and transcript when complete.  Transcribes an audio file (WAV, MP3, M4A, FLAC, OGG, WMA), detects 23 configurable types of user data in the transcript, and redacts audio segments containing PII. Returns the redacted audio, redacted transcript, detection results, and redacted segment timestamps.  Requires Managed Instance or Private Cloud deployment.
  # @param [Hash] opts the optional parameters
  # @option opts [DlpAudioRedactionRequest] :body Input request
  # @return [DlpBatchJobResult]
  describe 'redact_audio_batch_job test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
