=begin
#dlpapi

#Easily and directly scan and detect sensitive data (PII) in input text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

# Common files
require 'cloudmersive-dlp-api-client/api_client'
require 'cloudmersive-dlp-api-client/api_error'
require 'cloudmersive-dlp-api-client/version'
require 'cloudmersive-dlp-api-client/configuration'

# Models
require 'cloudmersive-dlp-api-client/models/dlp_advanced_detection_request'
require 'cloudmersive-dlp-api-client/models/dlp_advanced_detection_response'
require 'cloudmersive-dlp-api-client/models/dlp_advanced_document_detection_request'
require 'cloudmersive-dlp-api-client/models/dlp_advanced_document_redaction_request'
require 'cloudmersive-dlp-api-client/models/dlp_advanced_document_redaction_response'
require 'cloudmersive-dlp-api-client/models/dlp_advanced_redaction_request'
require 'cloudmersive-dlp-api-client/models/dlp_advanced_redaction_response'
require 'cloudmersive-dlp-api-client/models/dlp_detection_request'
require 'cloudmersive-dlp-api-client/models/dlp_detection_response'
require 'cloudmersive-dlp-api-client/models/dlp_document_detection_request'
require 'cloudmersive-dlp-api-client/models/dlp_document_redaction_request'
require 'cloudmersive-dlp-api-client/models/dlp_document_redaction_response'
require 'cloudmersive-dlp-api-client/models/dlp_redaction_request'
require 'cloudmersive-dlp-api-client/models/dlp_redaction_response'
require 'cloudmersive-dlp-api-client/models/redacted_page_info'

# APIs
require 'cloudmersive-dlp-api-client/api/detect_api'
require 'cloudmersive-dlp-api-client/api/redact_api'

module CloudmersiveDlpApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveDlpApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
